AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Budgets Template for Cost Management and Alerts

Parameters:
  BudgetName:
    Type: String
    Default: MonthlyAccountBudget
    Description: Name of the budget

  BudgetAmount:
    Type: Number
    Default: 100
    Description: Monthly budget amount in USD
    MinValue: 1

  AlertThreshold80:
    Type: Number
    Default: 80
    Description: First alert threshold percentage
    MinValue: 1
    MaxValue: 100

  AlertThreshold100:
    Type: Number
    Default: 100
    Description: Second alert threshold percentage
    MinValue: 1
    MaxValue: 200

  AlertThreshold120:
    Type: Number
    Default: 120
    Description: Third alert threshold (forecasted) percentage
    MinValue: 1
    MaxValue: 300

  NotificationEmail:
    Type: String
    Description: Email address for budget notifications
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

  SNSTopicArn:
    Type: String
    Default: ''
    Description: Optional SNS Topic ARN for budget notifications

Conditions:
  HasSNSTopic: !Not [!Equals [!Ref SNSTopicArn, '']]

Resources:
  # Monthly Cost Budget
  MonthlyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Ref BudgetName
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref BudgetAmount
          Unit: USD
        CostTypes:
          IncludeTax: true
          IncludeSubscription: true
          UseBlended: false
          IncludeRefund: false
          IncludeCredit: false
          IncludeUpfront: true
          IncludeRecurring: true
          IncludeOtherSubscription: true
          IncludeSupport: true
          IncludeDiscount: true
          UseAmortized: false
      NotificationsWithSubscribers:
        # 80% Actual Spend Alert
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThreshold80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        # 100% Actual Spend Alert
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThreshold100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
        # 120% Forecasted Spend Alert
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThreshold120
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail

  # EC2 Service Budget
  EC2ServiceBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub '${BudgetName}-EC2'
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref BudgetAmount
          Unit: USD
        CostFilters:
          Service:
            - Amazon Elastic Compute Cloud - Compute
        CostTypes:
          IncludeTax: true
          IncludeSubscription: true
          UseBlended: false
          IncludeRefund: false
          IncludeCredit: false
          IncludeUpfront: true
          IncludeRecurring: true
          IncludeOtherSubscription: true
          IncludeSupport: true
          IncludeDiscount: true
          UseAmortized: false
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThreshold80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail

  # RDS Service Budget
  RDSServiceBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub '${BudgetName}-RDS'
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref BudgetAmount
          Unit: USD
        CostFilters:
          Service:
            - Amazon Relational Database Service
        CostTypes:
          IncludeTax: true
          IncludeSubscription: true
          UseBlended: false
          IncludeRefund: false
          IncludeCredit: false
          IncludeUpfront: true
          IncludeRecurring: true
          IncludeOtherSubscription: true
          IncludeSupport: true
          IncludeDiscount: true
          UseAmortized: false
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThreshold80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail

Outputs:
  MonthlyBudgetName:
    Description: Name of the monthly budget
    Value: !Ref BudgetName

  EC2BudgetName:
    Description: Name of the EC2 service budget
    Value: !Sub '${BudgetName}-EC2'

  RDSBudgetName:
    Description: Name of the RDS service budget
    Value: !Sub '${BudgetName}-RDS'
