AWSTemplateFormatVersion: '2010-09-09'
Description: IAM users with Admin and ReadOnly access policies

Parameters:
  AdminUserName:
    Type: String
    Default: admin-user
    Description: Username for the admin IAM user

  ReadOnlyUserName:
    Type: String
    Default: readonly-user
    Description: Username for the read-only IAM user

Resources:
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${AdminUserName}-group'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub '${ReadOnlyUserName}-group'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref AdminUserName
      Groups:
        - !Ref AdminGroup
      Tags:
        - Key: Purpose
          Value: Administrative access
        - Key: ManagedBy
          Value: ControlTower

  ReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref ReadOnlyUserName
      Groups:
        - !Ref ReadOnlyGroup
      Tags:
        - Key: Purpose
          Value: Read-only access
        - Key: ManagedBy
          Value: ControlTower

  AdminUserAddToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref AdminGroup
      Users:
        - !Ref AdminUser

  ReadOnlyUserAddToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref ReadOnlyGroup
      Users:
        - !Ref ReadOnlyUser

Outputs:
  AdminUserArn:
    Description: ARN of the admin IAM user
    Value: !GetAtt AdminUser.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AdminUserArn'

  ReadOnlyUserArn:
    Description: ARN of the read-only IAM user
    Value: !GetAtt ReadOnlyUser.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ReadOnlyUserArn'

  AdminGroupArn:
    Description: ARN of the admin IAM group
    Value: !GetAtt AdminGroup.Arn

  ReadOnlyGroupArn:
    Description: ARN of the read-only IAM group
    Value: !GetAtt ReadOnlyGroup.Arn
